package com.fosun

import com.fosun.tableObjects.*;

 
rule "age from birthday"
ruleflow-group "Group12"	
salience 10
    when  	
        m: YongAn(cleanedPerson.getBirthDay() != null && cleanedPerson.getBirthDay() != "Not Valid ID" && cleanedPerson.getAge() == 0 )
        
    then
        m.cleanedPerson.setAge(2017 - Integer.parseInt(m.cleanedPerson.getBirthDay().substring(0,4)));
        update(m);
end
