package com.fosun

import com.fosun.tableObjects.*;

 
rule "decade < 14"
ruleflow-group "Group13"	
salience 10
    when  	
        m: YongAn(cleanedPerson.age > 0 && cleanedPerson.age < 14 && cleanedPerson.decade == null)
    then
        m.cleanedPerson.decade = "<14";
        update(m);
end

rule "decade 15~18"
ruleflow-group "Group13"	
salience 10
    when  	
        m: YongAn(cleanedPerson.age > 15 && cleanedPerson.age < 18 && cleanedPerson.decade == null)
    then
        m.cleanedPerson.decade = "15~18";
        update(m);
end

rule "decade 19~24"
ruleflow-group "Group13"	
salience 10
    when  	
        m: YongAn(cleanedPerson.age > 19 && cleanedPerson.age < 24 && cleanedPerson.decade == null)
    then
        m.cleanedPerson.decade = "19~24";
        update(m);
end

rule "decade 25~29"
ruleflow-group "Group13"	
salience 10
    when  	
        m: YongAn(cleanedPerson.age > 25 && cleanedPerson.age < 29 && cleanedPerson.decade == null)
    then
        m.cleanedPerson.decade = "25~29";
        update(m);
end

rule "decade 30~35"
ruleflow-group "Group13"	
salience 10
    when  	
        m: YongAn(cleanedPerson.age > 30 && cleanedPerson.age < 35 && cleanedPerson.decade == null)
    then
        m.cleanedPerson.decade = "30~35";
        update(m);
end

rule "decade 36~39"
ruleflow-group "Group13"	
salience 10
    when  	
        m: YongAn(cleanedPerson.age > 36 && cleanedPerson.age < 39 && cleanedPerson.decade == null)
    then
        m.cleanedPerson.decade = "36~39";
        update(m);
end

rule "decade 40~44"
ruleflow-group "Group13"	
salience 10
    when  	
        m: YongAn(cleanedPerson.age > 40 && cleanedPerson.age < 44 && cleanedPerson.decade == null)
    then
        m.cleanedPerson.decade = "40~44";
        update(m);
end

rule "decade 45~50"
ruleflow-group "Group13"	
salience 10
    when  	
        m: YongAn(cleanedPerson.age > 45 && cleanedPerson.age < 50 && cleanedPerson.decade == null)
    then
        m.cleanedPerson.decade = "45~50";
        update(m);
end

rule "decade 51~54"
ruleflow-group "Group13"	
salience 10
    when  	
        m: YongAn(cleanedPerson.age > 51 && cleanedPerson.age < 54 && cleanedPerson.decade == null)
    then
        m.cleanedPerson.decade = "51~54";
        update(m);
end

rule "decade 55~59"
ruleflow-group "Group13"	
salience 10
    when  	
        m: YongAn(cleanedPerson.age > 55 && cleanedPerson.age < 59 && cleanedPerson.decade == null)
    then
        m.cleanedPerson.decade = "55~59";
        update(m);
end

rule "decade 60~64"
ruleflow-group "Group13"	
salience 10
    when  	
        m: YongAn(cleanedPerson.age > 60 && cleanedPerson.age < 64 && cleanedPerson.decade == null)
    then
        m.cleanedPerson.decade = "60~64";
        update(m);
end

rule "decade > 65"
ruleflow-group "Group13"	
salience 10
    when  	
        m: YongAn(cleanedPerson.age > 65 && cleanedPerson.decade == null)
    then
        m.cleanedPerson.decade = ">65";
        update(m);
end
