package com.fosun

import com.fosun.tableObjects.*;

 
rule "decade < 14"
ruleflow-group "Group13"	
salience 10
    when  	
        m: YongAn(cleanedPerson.getAge() > 0 && cleanedPerson.getAge() < 15 && cleanedPerson.getDecade() == null)
    then
        m.cleanedPerson.setDecade("<14");
        update(m);
end

rule "decade 15~18"
ruleflow-group "Group13"	
salience 10
    when  	
        m: YongAn(cleanedPerson.getAge() >= 15 && cleanedPerson.getAge() < 19 && cleanedPerson.getDecade() == null)
    then
        m.cleanedPerson.setDecade("15~18");
        update(m);
end

rule "decade 19~24"
ruleflow-group "Group13"	
salience 10
    when  	
        m: YongAn(cleanedPerson.getAge() >= 19 && cleanedPerson.getAge() < 25 && cleanedPerson.getDecade() == null)
    then
        m.cleanedPerson.setDecade("19~24");
        update(m);
end

rule "decade 25~29"
ruleflow-group "Group13"	
salience 10
    when  	
        m: YongAn(cleanedPerson.getAge() >= 25 && cleanedPerson.getAge() < 30 && cleanedPerson.getDecade() == null)
    then
        m.cleanedPerson.setDecade("25~29");
        update(m);
end

rule "decade 30~35"
ruleflow-group "Group13"	
salience 10
    when  	
        m: YongAn(cleanedPerson.getAge() >= 30 && cleanedPerson.getAge() < 36 && cleanedPerson.getDecade() == null)
    then
        m.cleanedPerson.setDecade("30~35");
        update(m);
end

rule "decade 36~39"
ruleflow-group "Group13"	
salience 10
    when  	
        m: YongAn(cleanedPerson.getAge() >= 36 && cleanedPerson.getAge() < 40 && cleanedPerson.getDecade() == null)
    then
        System.out.println(m.cleanedPerson.getAge());
        m.cleanedPerson.setDecade("36~39");
        update(m);
end

rule "decade 40~44"
ruleflow-group "Group13"	
salience 10
    when  	
        m: YongAn(cleanedPerson.getAge() >= 40 && cleanedPerson.getAge() < 45 && cleanedPerson.getDecade() == null)
    then
        m.cleanedPerson.setDecade("40~44");
        update(m);
end

rule "decade 45~50"
ruleflow-group "Group13"	
salience 10
    when  	
        m: YongAn(cleanedPerson.getAge() >= 45 && cleanedPerson.getAge() < 51 && cleanedPerson.getDecade() == null)
    then
        m.cleanedPerson.setDecade("45~50");
        update(m);
end

rule "decade 51~54"
ruleflow-group "Group13"	
salience 10
    when  	
        m: YongAn(cleanedPerson.getAge() >= 51 && cleanedPerson.getAge() < 55 && cleanedPerson.getDecade() == null)
    then
        m.cleanedPerson.setDecade("51~54");
        update(m);
end

rule "decade 55~59"
ruleflow-group "Group13"	
salience 10
    when  	
        m: YongAn(cleanedPerson.getAge() >= 55 && cleanedPerson.getAge() < 60 && cleanedPerson.getDecade() == null)
    then
        m.cleanedPerson.setDecade("55~59");
        update(m);
end

rule "decade 60~64"
ruleflow-group "Group13"	
salience 10
    when  	
        m: YongAn(cleanedPerson.getAge() >= 60 && cleanedPerson.getAge() < 65 && cleanedPerson.getDecade() == null)
    then
        m.cleanedPerson.setDecade("60~64");
        update(m);
end

rule "decade > 65"
ruleflow-group "Group13"	
salience 10
    when  	
        m: YongAn(cleanedPerson.getAge() >= 65 && cleanedPerson.getDecade() == null)
    then
        m.cleanedPerson.setDecade(">65");
        update(m);
end
