package com.fosun

import com.fosun.tableObjects.*;
import cc.shanruifeng.functions.card.*

 
rule "get gender"
ruleflow-group "Group11"	
salience 20
    when  	
        m: YongAn(cleanedPerson.gender == null && gender != null)
    then
        m.cleanedPerson.gender = m.gender;
        update(m);
end


rule "get gender from id"
ruleflow-group "Group11"    
salience 10
    when    
        m: YongAn(id_sex != null && cleanedPerson.gender == null && gender == null)
    then
        m.cleanedPerson.gender = m.id_sex;
        update(m);
end
